### ISSUE TITLE
Understanding the configuration

### ISSUE THREAD

**Issue by jasondiesel** [gniemetz/automount#1]
In the "automount.sh" file, there are two sections at the beginning  that refer to what looks like two files. Is the correct procedure, to copy/paste these commented blocks and paste them as new files in the respective locations, then edit them, then copy automout.sh to its correct location, chmod it, then it should run fine? Is that correct? Just missing a little documentation as to the configuration.

**Comment by gniemetz** [comment]
Hi Jason!

Yes, thats right. The automount.sh is still work in progress and it lacks
of documentation.

best regards
Gerd

2017-01-23 16:17 GMT+01:00 Jason Diesel <notifications@github.com>:

**Comment by jasondiesel** [comment]
Ok, I am excited about this, so can help. This is something I have been struggling for a while, - not wanting to store any passwords in files - the easy way.... A question then: 

In the following line:
<key>CommonMaxRetryInSeconds</key>
       <integer>COMMONMAXRETRYINSECONDS (eg. 30)</integer>

Should we replace 
"<integer>COMMONMAXRETRYINSECONDS (eg. 30)</integer>" 
and make that 
"<integer>30</integer>"

Or are the capital letters important? ie: 
"<integer>COMMONMAXRETRYINSECONDS 30</integer>"

**Comment by jasondiesel** [comment]
Git removed my comment blocks:....

In the following line:
`
# <key>CommonMaxRetryInSeconds</key>
#       <integer>COMMONMAXRETRYINSECONDS (eg. 30)</integer>
`

Should we replace:
`
#       <integer>COMMONMAXRETRYINSECONDS (eg. 30)</integer>
`
and make that
`
#       <integer>30</integer>
`

Or are the capital letters important? ie:
`
#       <integer>COMMONMAXRETRYINSECONDS 30</integer>
`

Just understanding your parameter procedure..

**Comment by gniemetz** [comment]
The capital letters are placeholders, and the value 30 for the key `CommonMaxRetryInSeconds` is the time ping should try to reach the server.
