### ISSUE TITLE
Mount commands in the script may need to be changed for Sierra 10.12.3

### ISSUE THREAD

**Issue by jason1365** [gniemetz/automount#2]
I had to modify line 419 to get smb mounting to work because the command seems to be mount_smbfs (not mount_smb).

$ mount_
mount_acfs    mount_apfs    mount_cddafs  mount_exfat   mount_ftp     mount_msdos   mount_ntfs    mount_udf     
mount_afp     mount_cd9660  mount_devfs   mount_fdesc   mount_hfs     mount_nfs     mount_smbfs   mount_webdav

**Comment by gniemetz** [comment]
Thanks for finding, new version 0.90.2 uploaded
