### ISSUE TITLE
Couple problems with ${USER}, ${HOME}, ${LOGINNAME}, etc.

### ISSUE THREAD

**Issue by jasondiesel** [gniemetz/automount#5]
On MacOS Sierra, not sure about previous or other versions...

But line 346 of automount.sh calls:
CommonMaxRetryInSeconds="$(/usr/libexec/PlistBuddy -c "Print CommonMaxRetryInSeconds" "${AUTOMOUNTPLIST_AFN}" 2>/dev/null)"

Which references:
declare -r AUTOMOUNTPLIST_AFN="${USERHOME}/Library/Preferences/it.niemetz.automount.plist"

${USERHOME} on my system is blank.

So I changed to:
declare -r AUTOMOUNTPLIST_AFN="${HOME}/Library/Preferences/it.niemetz.automount.plist"

This works correctly.

I ended up doing a global replace on all occurrences, now it works great.

I ran this manually to see what the output was: (With ${HOME} it works properly.)
/usr/libexec/PlistBuddy -c "Print CommonMaxRetryInSeconds" "${HOME}/Library/Preferences/it.niemetz.automount.plist"

**Comment by gniemetz** [comment]
This should'nt be the case, the variables are set via the `id` command.
What OS release are you using?
Please set the variable `DEBUG` to `true` and post the output, **don't forget to clear out the password**

Thank you

**Comment by gniemetz** [comment]
Sometimes the `dscl` command returns the value of a query in the second line, so all the variables filled via this command could fail. In version 0.90.9 in dev-Brach i changed the way those variables are initialized
Hope this helps

regards
Gerd

**Comment by gniemetz** [comment]
Any updates on this?

**Comment by gniemetz** [comment]
I suppose it's ok, so i close the issue
