### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by ipa64** [gniemetz/automount#9]
Hi, 
I'm trying to use your script.
I got notification: 2017-03-16 16:41:21 +0100|46628|Info|All shares mountd successfully
But in fact nothing was mounted.
Please don't you have a preference file for sample ?
Thanks

**Comment by ipa64** [comment]
Even with wrong share name or wrong ip range

**Comment by gniemetz** [comment]
Please set the ```DEBUG``` variable to ```true``` an post the output of ```automount.sh --mountall```, **but don't forget to clear out the password(s)!**
And also your ```~/Library/Preferences/it.niemetz.automount.plist``` (or send PM if you don't want  others to see your shares)

Thanks
Gerd

**Comment by ipa64** [comment]
Hi Gerd,
Thanks for your support.

In attachment you will find the output of auto mount.sh

Mountlist seems to be null!

And a question, my NAS account login is not the same than my mac account, so I don’t understand in which record the script is trying to get the password.


Here my ~/Library/Preferences/it.niemetz.automount.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CommonMaxRetryInSeconds</key>
	<integer>10</integer>
	<key>CommonValidIPRanges</key>
	<string>192.168.1</string>
	<key>CommonAccount</key>
	<string>Proxy64 (optional)</string>
	<key>CommonMountOptions</key>
	<string>COMMONMOUNTOPTIONS (optional, separated by comma, eg. nodev,nosuid)</string>
	<key>Mountlist</key>
	<array>
		<dict>
			<key>MaxRetryInSeconds</key>
			<integer>MAXRETRYINSECONDS (optional)</integer>
			<key>ValidIPRanges</key>
			<string>VALIDIPRANGES (optional, separated by comma, eg. 10.0.0,192.168.0)</string>
			<key>MountOptions</key>
			<string>MOUNTOPTIONS (optional)</string>
			<key>Protocol</key>
			<string>afp</string>
			<key>Domain</key>
			<string>DOMAIN (optional)</string>
			<key>Account</key>
			<string>Proxy64</string>
			<key>Server</key>
			<string>192.168.1.100</string>
			<key>Share</key>
			<string>docker</string>
			<key>MountPoint</key>
			<string>MOUNTPOINT (optional)</string>
		</dict>
	</array>
</dict>
</plist>


Thanks
Have a nice day
Patrick

**Comment by gniemetz** [comment]
Here is a minimum sample of ```~/Library/Preferences/it.niemetz.automount.plist``` for mounting the ```your_share``` from ```your_nas``` (either IP address or DNS name) with user ```your_user``` and protocol ```your_protocol``` (usually ```afp``` or ```smb```)
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Mountlist</key>
	<array>
		<dict>
			<key>Protocol</key>
			<string>your_protocol</string>
			<key>Account</key>
			<string>your_user</string>
			<key>Server</key>
			<string>your_nas</string>
			<key>Share</key>
			<string>your_share</string>
		</dict>
	</array>
</dict>
</plist>
```
Replace the sample values (```your_...```) with your data, optionally check the plist for errors with ```plutil -lint ~/Library/Preferences/it.niemetz.automount.plist``` (you shoud get an ```OK```)

Next, add ```your_user``` to the keychain with ```automount.sh --addpassword --protocol your_protocol --server yourserver --account your_user``` and give in the password

At last, run ```automount.sh --mountall``` and hopefully your share get's mounted

If mounting doesn't work, see my comment above and try to debug where the problem is

HTH
Gerd

**Comment by ipa64** [comment]
Now all is working very well :-)
Thanks a lot !
